# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-02-13 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mezzanine_agenda', '0026_auto_20170823_1825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventprice',
            options={'ordering': ('-value',), 'verbose_name': 'Event price', 'verbose_name_plural': 'Event prices'},
        ),
    ]
