# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-05 23:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mezzanine_agenda', '0028_auto_20180926_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='event',
            name='mentions_fr',
        ),
        migrations.RemoveField(
            model_name='event',
            name='no_price_comments_fr',
        ),
        migrations.RemoveField(
            model_name='event',
            name='sub_title_fr',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='eventcategory',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='eventcategory',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='eventlocation',
            name='description_fr',
        ),
    ]
