# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-31 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezzanine_agenda', '0029_auto_20190117_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventlocation',
            name='site',
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='slug',
            field=models.CharField(blank=True, help_text='Leave blank to have the URL auto-generated from the filed defined by slug_field_name.', max_length=2000, null=True, verbose_name='URL'),
        ),
    ]
