# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-07 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mezzanine_agenda', '0028_auto_20180926_1235'),
        ('mezzanine_agenda', '0029_auto_20180403_1406'),
    ]

    operations = [
    ]
