# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-08-06 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezzanine_agenda', '0030_merge_20190107_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlocation',
            name='place_id',
            field=models.TextField(blank=True, help_text='Google Place ID (unique identifier)', null=True),
        ),
    ]
