# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-21 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mezzanine_agenda', '0031_eventcategory_site'),
        ('mezzanine_agenda', '0028_auto_20180329_1610'),
    ]

    operations = [
    ]
