# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-11-04 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mezzanine_agenda', '0037_auto_20190703_1044'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventShop',
            new_name='ExternalShop',
        ),
        migrations.AlterModelOptions(
            name='externalshop',
            options={'verbose_name': 'External shop', 'verbose_name_plural': 'External shops'},
        ),
    ]
