# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-11-04 14:53
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mezzanine_agenda', '0038_auto_20191104_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalshop',
            name='content',
            field=mezzanine.core.fields.RichTextField(blank=True, null=True, verbose_name='Content'),
        ),
    ]
