# Generated by Django 2.2.24 on 2021-08-23 15:42

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mezzanine_agenda', '0042_auto_20200107_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='brochure',
            field=mezzanine.core.fields.FileField(blank=True, max_length=1024, upload_to='brochures', verbose_name='brochure'),
        ),
    ]
