# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-08 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mezzanine_agenda', '0033_auto_20190326_1649'),
        ('mezzanine_agenda', '0042_auto_20200107_1747'),
    ]

    operations = [
    ]
