# Generated by Django 3.2.18 on 2023-04-24 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mezzanine_agenda', '0032_event_meta_category'),
        ('mezzanine_agenda', '0043_auto_20210823_1742'),
    ]

    operations = [
    ]
