# Generated by Django 3.2.19 on 2023-06-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0131_alter_project_topics'),
        ('mezzanine_agenda', '0045_alter_event_meta_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='events', to='organization_projects.ProjectTopic', verbose_name='topics'),
        ),
    ]
