# Generated by Django 3.2.19 on 2023-08-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezzanine_agenda', '0046_event_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='wether this topic is featured for external applications'),
        ),
    ]
